# Generated by Django 4.1a1 on 2022-06-14 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='slug'),
        ),
    ]
